- name: Installation du jdk8
  package: name=openjdk-8-jdk-headless state=present

- name: Création du compte TomEE
  user:
    name: tomee
    shell: /bin/false
    system: yes
    home: '{{tomee_home}}'

- name: Installation de TomEE
  unarchive:
    src: '{{tomee_url}}'
    dest: '{{tomee_home}}'
    remote_src: True
    extra_opts: "--strip-components=1"
    creates: '{{tomee_home}}/bin/startup.sh'
    group: tomee
    owner: tomee

- name: Copie du fichier unit Systemd pour TomEE
  template:
    src: 'roles/tomee-server/templates/tomee.service'
    dest: '/etc/systemd/system/tomee.service'
  notify:
    - activer TomEE

- name: Vérification que TomEE est actif
  service: state=started name=tomee

- copy: Copie du fichier tomcat-users
    src: 'tomcat-users.xml'
    dest: '{{tomee_access_file}}'
    owner: tomee
    group: tomee

- copy: Copie du fichier manager
    src: 'manager.xml'
    dest: '{{tomee_context_file}}'
    owner: tomee
    group: tomee

- service: Restart du service TomEE
    name: tomee
    state: restarted
